site_name: Platt
site_author: Maddy Duran
site_url: https://cole-trapnell-lab.github.io/platt
nav:
  - Overview: index.md
  - Background: background.md
  - Installation: install.md
  - Kinetics: kinetics.md
  - Graphs: graphs.md
  - DEGs: deg.md
  - DvEGs: dveg.md
  - Plotting: plotting.md
  - Reference: reference.md

theme:
  palette:
    scheme: trapnell
    accent: teal
  name: material
  language: en
  features: 
    - content.code.copy
#  logo: assets/ben_logo_embryo.png

repo_url: https://github.com/cole-trapnell-lab/platt
markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy 2025 <a href="https://github.com/cole-trapnell-lab"  target="_blank" rel="noopener">Cole Trapnell</a>
